INSERT INTO ELectronics_Gadgets (GADGET_ID, GADGET_NAME, GADGET_PRICE) VALUES (101, 'SAMSUNG', 30000.00);
INSERT INTO ELectronics_Gadgets (GADGET_ID, GADGET_NAME, GADGET_PRICE) VALUES (102, 'APPLE', 150000.00);
INSERT INTO ELectronics_Gadgets (GADGET_ID, GADGET_NAME, GADGET_PRICE) VALUES (103, 'MICROMAX', 15000.00);
INSERT INTO ELectronics_Gadgets (GADGET_ID, GADGET_NAME, GADGET_PRICE) VALUES (104, 'OPPO', 25000.00);
